image: quay.io/cldevops/pipeline-tools
options:
  docker: true
clone:
  depth: full

step_definitions:
- lint: &lint
    name: Lint
    image: node:12-buster
    caches: ["node"]
    script:
      - yarn
      - yarn lint
- build: &build
    name: Build
    image: node:12-buster
    caches: ["node"]
    script:
      - yarn
      - yarn build
- mirror_to_github: &mirror_to_github
    name: mirror_to_github
    script:
    - export MIRROR_TO_GITHUB=true
    - make mirror-to-github

pipelines:
  pull-requests:
    "**":
      - step: *build
  branches:
    master:
    - step: *mirror_to_github
